project_id = "rqzkzstltfdtypkvriue"

[functions.get-dashboard-stats]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.get-performance-benchmarks]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true